FROM nginx:alpine
RUN rm -f /etc/nginx/conf.d/default.conf
# Copying static content happens via volume in docker-compose.yml
# Copying config happens via volume in docker-compose.yml
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
